[package]
name = "wget"
version = "0.1.0"
edition = "2021"
authors = ["Laura"]

[dependencies]
clap = "2.26.0"
indicatif = "0.17.8"
url = "2.2"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }